spring.application.name=hoangquan_2604

portfolio.name=Nguyen Phan Hoang Quan
portfolio.mssv=2280602604
portfolio.lop=22DTHH2
portfolio.email=hq16101971@gmail.com
portfolio.phone=0123456789
portfolio.bio=Sinh Vien Nganh Cong Nghe Thong Tin

# MySQL - dùng biến môi trường khi chạy Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hoangquan_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:apppass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
